name: Run Docs
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
          node-version: '20'

      - name: Install Packages
        run: npm install

      - name: Docs
        run: npm run docs
