name: Lint
on: [push, workflow_dispatch]

jobs:
  build:
    name: Lint on Node.js ${{ matrix.node-version }} and MongoDB ${{ matrix.mongodb-package-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        mongodb-package-version: [6]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - name: Install mongodb
        run: npm install mongodb@${{ matrix.mongodb-package-version }}

      - name: Run Lint
        run: npm run lint
