name: Test
on: [push, workflow_dispatch]

jobs:
  build:
    name: Test on Node ${{ matrix.node-version }}, MongoDB ${{ matrix.mongodb-version }}, library ${{ matrix.mongodb-package-version }}
    runs-on: ubuntu-latest
    env:
      USE_MONGODB: true
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
        mongodb-version: [5, 6]
        mongodb-package-version: [6]
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install Packages
        run: npm install

      - name: Install mongodb
        run: npm install mongodb@${{ matrix.mongodb-package-version }}

      - name: Test
        run: npm run test
        env:
          CI: true
